# Generated by Django 4.1.7 on 2024-01-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_payments_name_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='firstApt',
            field=models.BooleanField(default=True),
        ),
    ]
