# Generated by Django 4.1.7 on 2023-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='didPayed',
            field=models.BooleanField(default=False),
        ),
    ]
